version: "3.8"

services:
  web:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      nm-mongodb:
        condition: service_healthy
    env_file:
      - .env.local
    environment:
      - MONGODB_URI=mongodb://nm-mongodb:27017/nm-system

  nm-mongodb:
    image: mongo:7
    container_name: nm-mongodb
    ports:
      - "27017:27017"
    volumes:
      - nm-mongodb-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nm-mongodb-data:
    external: true
